import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PropsWithChildren } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}

// export default function RootLayout({
//   children,
// }: PropsWithChildren) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.className} bg-gray-dark`}>
      // <div className="container2 xl:block hidden">
      //     {children}
      //   </div>
//         <div className="xl:hidden block">
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }
