import type { Metadata } from "next";
import Navigation from "@/components/Navigation"
import Footer from "@/components/Footer"
import localFont from "next/font/local";
import "../globals.css";
import "../Style.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
    // <html lang="en">
    //   <body
    //     className={` antialiased`}
    //   >
    //     {children}
    //   </body>
    // </html>
//   );
// }
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
 

  return (
     <div className="">
     <Navigation/>
      {children}
      <Footer/>
      </div>
  );
}